{% set version = "0.1.5" %}

package:
  name: robotframework-axelibrary
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/r/robotframework-axelibrary/robotframework-axelibrary-{{ version }}.tar.gz
    sha256: 12f3f5895ab7a9770df6390ceefa6a8de8179b8a35bcfe6a224a32c0520765ad
build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - axe-selenium-python
    - python >={{ python_min }}
    - robotframework

test:
  imports:
    - AxeLibrary
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adiralashiva8/robotframework-axelibrary
  summary: Robot Framework keyword library wrapper around axe-selenium-python library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
